CREATE TABLE `user` (
    `id` int NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    `role_id` int NOT NULL DEFAULT '0' COMMENT '角色ID',
    `dept_id` int NOT NULL DEFAULT '0' COMMENT '部门ID',

    `machine_code` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '机器码',
    `number` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '编号',
    `customer` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '客户',
    `wagon_number` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '车号',
    `material` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '物资',
    `net_weight` decimal(11,3) NOT NULL DEFAULT '0.000' COMMENT '净重',
    `weight_deduction` decimal(11,3) NOT NULL DEFAULT '0.000' COMMENT '扣重',
    `deduction_rate` decimal(11,2) DEFAULT NULL COMMENT '扣率',
    `real_weight` decimal(11,3) NOT NULL DEFAULT '0.000' COMMENT '实重',
    `weighing_times` int NOT NULL DEFAULT '0' COMMENT '称重次数',
    `is_finish` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否称重完成',
    `is_valid` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否有效',
    `spare` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '备用',
    `remarks` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '备注',
    `gross_weight` decimal(11,3) NOT NULL DEFAULT '0.000' COMMENT '毛重',
    `gross_weight_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '毛重日期',
    `gross_weight_scorer` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '毛重司磅员',
    `tare` decimal(11,3) NOT NULL DEFAULT '0.000' COMMENT '皮重',
    `tare_date` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '皮重日期',
    `tare_scorer` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '皮重司磅员',
    `insert_time` int NOT NULL DEFAULT '0' COMMENT '客户端数据录入时间戳',
    `is_delete` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否删除：0.未删除，1.已删除',
    `create_time` int NOT NULL DEFAULT '0' COMMENT '创建时间戳',
    `update_time` int NOT NULL DEFAULT '0' COMMENT '更新时间戳',
    PRIMARY KEY (`id`),
    KEY `user_id_index` (`user_id`),
    KEY `machine_code_index` (`machine_code`)
) ENGINE=InnoDB AUTO_INCREMENT=64750 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='称重记录表';